### PR TITLE
remove stdlibrandom, update to dune

### PR DESCRIPTION
**Pull request by hannesm**
as mentioned in #7, I plan to provide stdlibrandom in a separate repository.

could someone review the upgrade-to-dune (@samoht @emillon)? it used to define `name stdlibrandom`, which is not accurate. now, it uses `mirage_random` as name, and `mirage-random` as public_name (and the name in dune-project, is this correct? -- I don't understand why I need the name three times!?) and `wrapped = false` (so as earlier users can use `Mirage_random.C/S.xxx` directly).

### CODE REVIEW

**Comment by emillon** [comment]
The dune conversion looks OK. At the moment the reason you need to have the names in 3 places is the following:
- `public_name` is the name of the opam package
- `name` is the name of the ocaml library & main module
- the one in `dune-project` is used for `subst`

If `public_name` is equal to `name`, you can omit `name`. This is not possible here because the public name is not a valid ocaml module name. We might add automatic mangling for this kind of cases.

The `dune-project` one is also something that we can improve. I filed ocaml/dune#1456 to improve generation of the file so that it includes `(name)`.

Side note, since you have an explicit `Mirage_random` module I think that you can drop `(wrapped false)` - in that case it should generate a single module and not wrap anything.

**Comment by hannesm** [comment]
thanks @emillon, I removed the `wrapped false` from the dune file.  CI is failing due to reverse dependencies using the (now no longer existing) `Stdlibrandom` module, I'll adapt their upper bounds.

**Comment by hannesm** [comment]
I added some upper bounds to charrua-client (in opam-repository and their repository) -- this is good to go now!

**Comment by samoht** [comment]
LGTM

**Pull request merged**
